
CREATE TABLE action
  `b` double DEFAULT NULL,
  `s` int(11) DEFAULT NULL,
  `o` int(11) DEFAULT NULL,
  `des` varchar(255) DEFAULT NULL,
  `des_es` varchar(255) DEFAULT NULL,
  `event` varchar(128) DEFAULT NULL,
  `tfs` varchar(50) DEFAULT NULL,
  `tfs_zulu` varchar(50) DEFAULT NULL,
  `player` int(11) DEFAULT NULL,
  `pitch` int(11) DEFAULT NULL,
  `url` varchar(255) DEFAULT NULL,
  `inning_side` varchar(32) DEFAULT NULL,
  `inning` int(11) DEFAULT NULL,
  `next_` varchar(32) DEFAULT NULL,
  `num` varchar(32) DEFAULT NULL,
  `score` varchar(32) DEFAULT NULL,
  `home_team_runs` varchar(32) DEFAULT NULL,
  `away_team_runs` varchar(32) DEFAULT NULL,
  `event2` varchar(128) DEFAULT NULL,
  `gameday_link` varchar(255) DEFAULT NULL



CREATE TABLE atbat 
  `pitcher` int(11) DEFAULT NULL,
  `batter` int(11) DEFAULT NULL,
  `num` int(11) DEFAULT NULL,
  `b` int(11) DEFAULT NULL,
  `s` int(11) DEFAULT NULL,
  `o` int(11) DEFAULT NULL,
  `start_tfs` int(11) DEFAULT NULL,
  `start_tfs_zulu` varchar(128) DEFAULT NULL,
  `stand` varchar(2) DEFAULT NULL,
  `b_height` varchar(4) DEFAULT NULL,
  `p_throws` varchar(2) DEFAULT NULL,
  `atbat_des` varchar(255) DEFAULT NULL,
  `atbat_des_es` varchar(255) DEFAULT NULL,
  `event` varchar(128) DEFAULT NULL,
  `score` int(11) DEFAULT NULL,
  `home_team_runs` int(11) DEFAULT NULL,
  `away_team_runs` int(11) DEFAULT NULL,
  `url` varchar(255) NOT NULL,
  `inning_side` varchar(16) DEFAULT NULL,
  `inning` int(11) DEFAULT NULL,
  `next_` varchar(16) DEFAULT NULL,
  `event2` varchar(128) DEFAULT NULL,
  `event3` varchar(128) DEFAULT NULL,
  `batter_name` varchar(128) DEFAULT NULL,
  `pitcher_name` varchar(128) DEFAULT NULL,
  `event4` varchar(128) DEFAULT NULL,
  `gameday_link` varchar(255) DEFAULT NULL,
  `date` date DEFAULT NULL



CREATE TABLE coach 
  `position` varchar(32) DEFAULT NULL,
  `first` varchar(32) DEFAULT NULL,
  `last` varchar(32) DEFAULT NULL,
  `id` int(11) DEFAULT NULL,
  `num` int(11) DEFAULT NULL,
  `url` varchar(255) DEFAULT NULL,
  `name_abbrev` varchar(255) DEFAULT NULL,
  `type` varchar(255) DEFAULT NULL,
  `name` varchar(128) DEFAULT NULL,
  `gameday_link` varchar(255) DEFAULT NULL



CREATE TABLE game 
  `id` text,
  `venue` text,
  `game_pk` text,
  `time` text,
  `time_date` text,
  `time_date_aw_lg` text,
  `time_date_hm_lg` text,
  `time_zone` text,
  `ampm` text,
  `away_time` text,
  `away_time_zone` text,
  `away_ampm` text,
  `home_time` text,
  `home_time_zone` text,
  `home_ampm` text,
  `game_type` text,
  `tiebreaker_sw` text,
  `original_date` text,
  `time_zone_aw_lg` text,
  `time_zone_hm_lg` text,
  `time_aw_lg` text,
  `aw_lg_ampm` text,
  `tz_aw_lg_gen` text,
  `time_hm_lg` text,
  `hm_lg_ampm` text,
  `tz_hm_lg_gen` text,
  `venue_id` double DEFAULT NULL,
  `scheduled_innings` double DEFAULT NULL,
  `away_name_abbrev` text,
  `home_name_abbrev` text,
  `away_code` text,
  `away_file_code` text,
  `away_team_id` double DEFAULT NULL,
  `away_team_city` text,
  `away_team_name` text,
  `away_division` text,
  `away_league_id` double DEFAULT NULL,
  `away_sport_code` text,
  `home_code` text,
  `home_file_code` text,
  `home_team_id` double DEFAULT NULL,
  `home_team_city` text,
  `home_team_name` text,
  `home_division` text,
  `home_league_id` double DEFAULT NULL,
  `home_sport_code` text,
  `day` text,
  `gameday_sw` text,
  `double_header_sw` text,
  `away_games_back` text,
  `home_games_back` text,
  `away_games_back_wildcard` double DEFAULT NULL,
  `home_games_back_wildcard` text,
  `venue_w_chan_loc` text,
  `gameday_link` text,
  `away_win` double DEFAULT NULL,
  `away_loss` double DEFAULT NULL,
  `home_win` double DEFAULT NULL,
  `home_loss` double DEFAULT NULL,
  `game_data_directory` text,
  `league` text,
  `top_inning` text,
  `status` text,
  `ind` text,
  `inning` double DEFAULT NULL,
  `outs` double DEFAULT NULL,
  `away_team_runs` double DEFAULT NULL,
  `home_team_runs` double DEFAULT NULL,
  `away_team_hits` double DEFAULT NULL,
  `home_team_hits` double DEFAULT NULL,
  `away_team_errors` double DEFAULT NULL,
  `home_team_errors` double DEFAULT NULL,
  `away_team_hr` text,
  `home_team_hr` text,
  `away_team_sb` text,
  `home_team_sb` text,
  `away_team_so` text,
  `home_team_so` text,
  `mlbtv_link` text,
  `wrapup_link` text,
  `home_audio_link` text,
  `away_audio_link` text,
  `home_preview_link` text,
  `away_preview_link` text,
  `preview_link` text,
  `tv_station` text,
  `url` text,
  `description` text,
  `reason` text,
  `first_pitch_et` text,
  `url_scoreboard` text,
  `away_league_id_spring` tinyint(4) DEFAULT NULL,
  `away_split_squad` tinyint(4) DEFAULT NULL,
  `home_league_id_spring` tinyint(4) DEFAULT NULL,
  `home_split_squad` tinyint(4) DEFAULT NULL,
  `resume_date` text,
  `series` tinyint(4) DEFAULT NULL,
  `series_num` tinyint(4) DEFAULT NULL,
  `ser_home_nbr` tinyint(4) DEFAULT NULL,
  `ser_games` tinyint(4) DEFAULT NULL,
  `postseason_tv_link` tinyint(4) DEFAULT NULL,
  `game_nbr` text,
  `tbd_flag` text,
  `if_necessary` tinyint(4) DEFAULT NULL,
  `runner_on_base_status` text



CREATE TABLE hip 
  `des` text,
  `x` double DEFAULT NULL,
  `y` double DEFAULT NULL,
  `batter` double DEFAULT NULL,
  `pitcher` double DEFAULT NULL,
  `type` text,
  `team` text,
  `inning` double DEFAULT NULL,
  `url` text,
  `gameday_link` text


CREATE TABLE media 
  `type` varchar(16) DEFAULT NULL,
  `calendar_event_id` varchar(128) DEFAULT NULL,
  `start` varchar(128) DEFAULT NULL,
  `title` varchar(32) DEFAULT NULL,
  `has_mlbtv` varchar(32) DEFAULT NULL,
  `free` varchar(4) DEFAULT NULL,
  `media_state` varchar(32) DEFAULT NULL,
  `thumbnail` varchar(32) DEFAULT NULL,
  `url` varchar(255) DEFAULT NULL,
  `content_id` int(11) DEFAULT NULL,
  `topic_id` int(11) DEFAULT NULL,
  `headline` varchar(255) DEFAULT NULL,
  `gameday_link` varchar(255) DEFAULT NULL


CREATE TABLE pitch 
  `des` varchar(255) DEFAULT NULL,
  `des_es` varchar(255) DEFAULT NULL,
  `id` int(11) DEFAULT NULL,
  `type` varchar(1) DEFAULT NULL,
  `tfs` int(11) DEFAULT NULL,
  `tfs_zulu` varchar(255) DEFAULT NULL,
  `x` float DEFAULT NULL,
  `y` float DEFAULT NULL,
  `sv_id` varchar(128) DEFAULT NULL,
  `start_speed` float DEFAULT NULL,
  `end_speed` float DEFAULT NULL,
  `sz_top` float DEFAULT NULL,
  `sz_bot` float DEFAULT NULL,
  `pfx_x` float DEFAULT NULL,
  `pfx_z` float DEFAULT NULL,
  `px` float DEFAULT NULL,
  `pz` float DEFAULT NULL,
  `x0` float DEFAULT NULL,
  `y0` float DEFAULT NULL,
  `z0` float DEFAULT NULL,
  `vx0` float DEFAULT NULL,
  `vy0` float DEFAULT NULL,
  `vz0` float DEFAULT NULL,
  `ax` float DEFAULT NULL,
  `ay` float DEFAULT NULL,
  `az` float DEFAULT NULL,
  `break_y` float DEFAULT NULL,
  `break_angle` float DEFAULT NULL,
  `break_length` float DEFAULT NULL,
  `pitch_type` varchar(16) DEFAULT NULL,
  `type_confidence` float DEFAULT NULL,
  `zone` int(11) DEFAULT NULL,
  `nasty` int(11) DEFAULT NULL,
  `spin_dir` int(11) DEFAULT NULL,
  `spin_rate` int(11) DEFAULT NULL,
  `cc` varchar(255) DEFAULT NULL,
  `mt` varchar(255) DEFAULT NULL,
  `url` varchar(255) NOT NULL,
  `inning_side` varchar(16) DEFAULT NULL,
  `inning` int(11) DEFAULT NULL,
  `next_` varchar(32) DEFAULT NULL,
  `num` int(11) NOT NULL,
  `on_1b` int(11) DEFAULT NULL,
  `on_2b` int(11) DEFAULT NULL,
  `on_3b` int(11) DEFAULT NULL,
  `count` varchar(16) DEFAULT NULL,
  `gameday_link` varchar(255) DEFAULT NULL


CREATE TABLE player
  `id` int(11) DEFAULT NULL,
  `first` varchar(32) DEFAULT NULL,
  `last` varchar(32) DEFAULT NULL,
  `num` int(11) DEFAULT NULL,
  `boxname` varchar(32) DEFAULT NULL,
  `rl` varchar(2) DEFAULT NULL,
  `position` varchar(4) DEFAULT NULL,
  `status` varchar(2) DEFAULT NULL,
  `team_abbrev` varchar(8) DEFAULT NULL,
  `team_id` int(11) DEFAULT NULL,
  `parent_team_abbrev` varchar(4) DEFAULT NULL,
  `parent_team_id` int(11) DEFAULT NULL,
  `avg` int(11) DEFAULT NULL,
  `hr` int(11) DEFAULT NULL,
  `rbi` int(11) DEFAULT NULL,
  `url` varchar(255) DEFAULT NULL,
  `name_abbrev` varchar(4) DEFAULT NULL,
  `type` varchar(16) DEFAULT NULL,
  `name` varchar(128) DEFAULT NULL,
  `current_position` varchar(4) DEFAULT NULL,
  `bat_order` int(11) DEFAULT NULL,
  `game_position` varchar(4) DEFAULT NULL,
  `wins` int(11) DEFAULT NULL,
  `losses` int(11) DEFAULT NULL,
  `era` int(11) DEFAULT NULL,
  `gameday_link` varchar(255) DEFAULT NULL,
  `bats` varchar(2) DEFAULT NULL


CREATE TABLE po
  `des` varchar(255) DEFAULT NULL,
  `url` varchar(255) NOT NULL,
  `inning_side` varchar(16) DEFAULT NULL,
  `inning` int(11) DEFAULT NULL,
  `next_` varchar(32) DEFAULT NULL,
  `num` int(11) DEFAULT NULL,
  `gameday_link` varchar(255) DEFAULT NULL


CREATE TABLE runner
  `id` int(11) DEFAULT NULL,
  `start` varchar(2) DEFAULT NULL,
  `end` varchar(2) DEFAULT NULL,
  `event` varchar(32) DEFAULT NULL,
  `score` int(11) DEFAULT NULL,
  `rbi` int(11) DEFAULT NULL,
  `earned` int(11) DEFAULT NULL,
  `url` varchar(255) DEFAULT NULL,
  `inning_side` varchar(16) DEFAULT NULL,
  `inning` int(11) DEFAULT NULL,
  `next_` varchar(32) DEFAULT NULL,
  `num` int(11) DEFAULT NULL,
  `gameday_link` varchar(255) DEFAULT NULL



CREATE TABLE umpire
  `position` text,
  `ump_name` tinyint(4) DEFAULT NULL,
  `ump_id` tinyint(4) DEFAULT NULL,
  `url` text,
  `gameday_link` text,
  `name` text,
  `id` double DEFAULT NULL

